### ISSUE TITLE
Nvidiux on Manjaro (Arch linux)

### ISSUE THREAD

**Issue by ghtux** [RunGp/Nvidiux#13]
Hi there!

Switched to Manjaro Linux and tried to start nvidiux. In Manjaro the "/etc/X11/xorg.conf" doesn't exist. The config is /etc/X11/mhwd.d/nvidia.conf. I tried it with a symbolic link and with nvidiux creating a xorg.conf. Got this erros:

Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1532, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 256, in **init**
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 355, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 756, in initialiseData
    if self.piloteVersion >> 355:
TypeError: unsupported operand type(s) for >>: 'float' and 'int'

Used the package from AUR. Any idea how to solve that? I am using the 364.19 driver

**Comment by RunGp** [comment]
hi
Its a bug but i already fix it in next version
I finish the final step and send new 1.4 version today
