### ISSUE TITLE
1.4.1: ValueError: invalid literal for float(): 367.36.02

### ISSUE THREAD

**Issue by nRaecheR** [RunGp/Nvidiux#17]
The program crashes on start when trying to run with driver version 367.36.02 (dev driver).

```
Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1614, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 278, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 401, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 648, in initialiseData
    self.piloteVersion = float(out.split(':')[-1][1:])
ValueError: invalid literal for float(): 367.36.02
```

Note: Don't assume the driver version to be a float, it is in fact a string.

**Comment by RunGp** [comment]
Hi
Thanks for reporting.
Fix released on next minor version.
