### ISSUE TITLE
lots of errors

### ISSUE THREAD

**Issue by Cyberpangolin** [RunGp/Nvidiux#29]
Hi!

I encounter lots of python errors: typically

> ^[[ATraceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1002, in loadPrefWindow
    self.formSettings = Ui_Pref(0,self.pref,self)
  File "/usr/share/nvidiux/preference.py", line 81, in __init__
    self.setupUi()
  File "/usr/share/nvidiux/preference.py", line 643, in setupUi
    if self.listGpuMonitor[i][2] == "False":
IndexError: list index out of range

if I try to join any menu entry. 
the monitor seems broken too.

What is missing into my computer?
Just in case: I'm using a gtx980 FE

**Comment by ghost** [comment]
I am also getting lots of python errors. I reinstalled my arch linux and got a new graphic card now i'm getting python errors.

error
Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1608, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 284, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 397, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 882, in initialiseData
    if self.tabGpu[i].arch == "pascal" and self.driverVersion < 370.01:
AttributeError: 'NvidiuxApp' object has no attribute 'driverVersion'

I'm using the latest nvidia drivers , my card is gtx 1050ti

**Comment by RunGp** [comment]
Hi

Fix released try with 1.4.4 version of nvidiux
