### ISSUE TITLE
Unable to launch nvidiux on 18.10

### ISSUE THREAD

**Issue by HackerWolf** [RunGp/Nvidiux#40]
Hi! Just instelled nvidiux from ppa on my laptop running cosmic. It can't start:
`Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1871, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 306, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 472, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 702, in initialiseData
    compatibility = self.iscompatible()
  File "/usr/share/nvidiux/nvidiux.py", line 656, in iscompatible
    self.ui.checkBoxOptimus.setChecked(1)
AttributeError: 'Ui_MainWindow' object has no attribute 'checkBoxOptimus'`

HP Envy 17 equipped with GeForce GT 740M, running latest nvidia driver 415.13 from "Graphics Drivers" ppa, kernel 4.19.4-041904-generic from kernel.ubuntu.com (same if running last stock kernel from official repos).
Thanks in advance.

**Comment by Mattia98** [comment]
Same problem.

**Comment by RunGp** [comment]
Fix ready (version 2.1)
Release soon

**Comment by HackerWolf** [comment]
Soon™

**Comment by lbrunkho** [comment]
same issue on Mint 19 (ubuntu 18.10 base) terminal shows 
`Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1871, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 306, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 472, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 702, in initialiseData
    compatibility = self.iscompatible()
  File "/usr/share/nvidiux/nvidiux.py", line 656, in iscompatible
    self.ui.checkBoxOptimus.setChecked(1)
AttributeError: 'Ui_MainWindow' object has no attribute 'checkBoxOptimus'
`

**Comment by RunGp** [comment]
hi try with new release (deb file) : https://github.com/RunGp/Nvidiux/releases/tag/2.1
arch pkg is up to date
I will try update ubuntu ppa later...

**Comment by HackerWolf** [comment]
«Later»

20 days.. ok
