### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by jedenastka** [RunGp/Nvidiux#47]
1. Installed nvidiux on Debian Testing from DEB file and filled dependicies by `sudo aptitude install`.
2. Ran it using `nvidiux` command from terminal.
3. It asked me about generating xorg.conf. I clicked "yes".
5. Typed my password.
6. Got an error:
```
Wrong password
Error code: 7
```
7. Tried to run by `sudo nvidiux`.
8. The same until 5, where it didn't ask for password and it moved to 6.

```
System:
  Host: pecet Kernel: 4.19.0-2-amd64 x86_64 bits: 64 compiler: gcc v: 8.2.0 
  Desktop: KDE Plasma 5.14.5 Distro: Debian GNU/Linux buster/sid 
Machine:
  Type: Desktop System: Dell product: OptiPlex 790 v: 01 
  serial: <root required> 
  Mobo: Dell model: 0J3C2F v: A00 serial: <root required> BIOS: Dell v: A07 
  date: 09/10/2011 
CPU:
  Topology: Quad Core model: Intel Core i5-2400 bits: 64 type: MCP 
  arch: Sandy Bridge rev: 7 L2 cache: 6144 KiB 
  flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 24743 
  Speed: 1596 MHz min/max: 1600/3400 MHz Core speeds (MHz): 1: 1596 2: 1596 
  3: 1596 4: 1596 
Graphics:
  Device-1: NVIDIA GK106 [GeForce GTX 660] vendor: Micro-Star MSI 
  driver: nvidia v: 390.87 bus ID: 03:00.0 
  Display: x11 server: X.Org 1.20.3 driver: nvidia 
  resolution: 1280x1024~60Hz 
  OpenGL: renderer: GeForce GTX 660/PCIe/SSE2 v: 4.6.0 NVIDIA 390.87 
  direct render: Yes 
Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio 
  vendor: Dell driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
  Device-2: NVIDIA GK106 HDMI Audio vendor: Micro-Star MSI 
  driver: snd_hda_intel v: kernel bus ID: 03:00.1 
  Device-3: Logitech Webcam C270 type: USB driver: snd-usb-audio,uvcvideo 
  bus ID: 2-1.5:5 
  Sound Server: ALSA v: k4.19.0-2-amd64 
Network:
  Device-1: Intel 82579LM Gigabit Network vendor: Dell driver: e1000e 
  v: 3.2.6-k port: 4040 bus ID: 00:19.0 
  IF: eno1 state: down mac: 18:03:73:b0:66:be 
  IF-ID-1: wwan0 state: unknown mac: 1e:3d:93:46:e9:6d 
Drives:
  Local Storage: total: 1.26 TiB used: 147.90 GiB (11.5%) 
  ID-1: /dev/sda vendor: GOODRAM model: GOODRAM size: 111.79 GiB 
  ID-2: /dev/sdb vendor: Western Digital model: WD2500AAKX-753CA1 
  size: 232.89 GiB 
  ID-3: /dev/sdc type: USB vendor: Toshiba model: MQ01ABD100 
  size: 931.51 GiB 
  ID-4: /dev/sde type: USB vendor: Generic model: SD MMC size: 14.84 GiB 
Partition:
  ID-1: / size: 73.96 GiB used: 13.77 GiB (18.6%) fs: ext4 dev: /dev/sda5 
  ID-2: /home size: 205.96 GiB used: 128.15 GiB (62.2%) fs: ext4 
  dev: /dev/sdb5 
  ID-3: swap-1 size: 3.73 GiB used: 20.3 MiB (0.5%) fs: swap dev: /dev/sdb6 
Sensors:
  System Temperatures: cpu: 34.0 C mobo: N/A gpu: nvidia temp: 34 C 
  Fan Speeds (RPM): N/A gpu: nvidia fan: 30% 
Info:
  Processes: 254 Uptime: 7h 22m Memory: 7.75 GiB used: 5.48 GiB (70.7%) 
  Init: systemd runlevel: 5 Compilers: gcc: 8.2.0 Shell: zsh v: 5.7.1 
  inxi: 3.0.32
```

EDIT: You are looking for translators? I can translate to Polish.

EDIT2: I got same results when using cloned repo.

**Comment by Asuza** [comment]
I'm having similar issues. I can't get the application to start due to the password.
```
~ ▶︎︎ nvidiux
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
Authentication is needed to run `/usr/bin/python2' as the super user
Authenticating as: My Name,,, (myusername)
Password:
```
My password doesn't seem to work here.
If I use `sudo`, then this happens:
```
~ ▶︎︎ sudo nvidiux
Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1869, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 306, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 460, in createWidgets
    driver = float(result.split('|')[0])
ValueError: could not convert string to float: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <ti
```

**Comment by RunGp** [comment]
Hi 
I need find a machine with nvidia gpu and debian buster.
Stange get hmtl code here
As soon as i can reproduce this bug i will fix it.
