### ISSUE TITLE
nvidiux doesn't load

### ISSUE THREAD

**Issue by norbertom8** [RunGp/Nvidiux#54]
Here are the lines from my terminal... I hope they are useful.
Kind regards.

Traceback (most recent call last):
  File "/usr/share/nvidiux/nvidiux.py", line 1871, in <module>
    nvidiuxApp = NvidiuxApp(sys.argv[1:])
  File "/usr/share/nvidiux/nvidiux.py", line 306, in __init__
    self.createWidgets()
  File "/usr/share/nvidiux/nvidiux.py", line 472, in createWidgets
    self.initialiseData()
  File "/usr/share/nvidiux/nvidiux.py", line 702, in initialiseData
    compatibility = self.iscompatible()
  File "/usr/share/nvidiux/nvidiux.py", line 656, in iscompatible
    self.ui.checkBoxOptimus.setChecked(1)
AttributeError: 'Ui_MainWindow' object has no attribute 'checkBoxOptimus'

**Comment by norbertom8** [comment]
By the way, with drivers and cuda properly installed on linux mint 19.2
